In [1]:
import numpy as np
import pandas as pd

In [2]:
db = pd.read_csv('song_data.csv')

In [3]:
db.head()

Unnamed: 0                       Track.Name    Artist.Name           Genre  \
0           1                         Se�orita   Shawn Mendes    canadian pop   
1           2                            China       Anuel AA  reggaeton flow   
2           3    boyfriend (with Social House)  Ariana Grande       dance pop   
3           4  Beautiful People (feat. Khalid)     Ed Sheeran             pop   
4           5      Goodbyes (Feat. Young Thug)    Post Malone         dfw rap   

   Beats.Per.Minute  Energy  Danceability  Loudness..dB..  Liveness  Valence.  \
0               117      55            76              -6         8        75   
1               105      81            79              -4         8        61   
2               190      80            40              -4        16        70   
3                93      65            64              -8         8        55   
4               150      65            58              -4        11        18   

   Length.  Acousticness..  Speechiness.  Popularity  
0      191               4             3          79  
1      302               8             9          92  
2      186              12            46          85  
3      198              12            19          86  
4      175              45             7          94

In [4]:
db.columns

Index(['Unnamed: 0', 'Track.Name', 'Artist.Name', 'Genre', 'Beats.Per.Minute',
       'Energy', 'Danceability', 'Loudness..dB..', 'Liveness', 'Valence.',
       'Length.', 'Acousticness..', 'Speechiness.', 'Popularity'],
      dtype='object')

In [5]:
db.isnull().sum()

Unnamed: 0          0
Track.Name          0
Artist.Name         0
Genre               0
Beats.Per.Minute    0
Energy              0
Danceability        0
Loudness..dB..      0
Liveness            0
Valence.            0
Length.             0
Acousticness..      0
Speechiness.        0
Popularity          0
dtype: int64

In [6]:
#data is clean so no further operation needed

In [7]:
db.shape

(50, 14)

In [10]:
fea_columns = ['Track.Name', 'Artist.Name', 'Genre','Loudness..dB..','Energy','Length.']

In [11]:
db[fea_columns].head(3)

Track.Name    Artist.Name           Genre  \
0                       Se�orita   Shawn Mendes    canadian pop   
1                          China       Anuel AA  reggaeton flow   
2  boyfriend (with Social House)  Ariana Grande       dance pop   

   Loudness..dB..  Energy  Length.  
0              -6      55      191  
1              -4      81      302  
2              -4      80      186

In [12]:
def combine_features(fea_columns,data):
  combined_features = []
  for i in range(0, data.shape[0]):
    result = ''
    for feature in fea_columns:
      result = result + ' ' + str(data[feature][i]) 
    combined_features.append(result) 
  return combined_features 

In [13]:
db['combined_features'] = combine_features(fea_columns,db)

In [14]:
db.tail(3)

Unnamed: 0                                     Track.Name  \
47          48                                        Happier   
48          49                                  Call You Mine   
49          50  Cross Me (feat. Chance the Rapper & PnB Rock)   

         Artist.Name    Genre  Beats.Per.Minute  Energy  Danceability  \
47        Marshmello  brostep               100      79            69   
48  The Chainsmokers      edm               104      70            59   
49        Ed Sheeran      pop                95      79            75   

    Loudness..dB..  Liveness  Valence.  Length.  Acousticness..  Speechiness.  \
47              -3        17        67      214              19             5   
48              -6        41        50      218              23             3   
49              -6         7        61      206              21            12   

    Popularity                                  combined_features  
47          88               Happier Marshmello brostep -3 79 214  
48          88       Call You Mine The Chainsmokers edm -6 70 218  
49          82   Cross Me (feat. Chance the Rapper & PnB Rock)...

In [15]:
db.iloc[49]['combined_features']

' Cross Me (feat. Chance the Rapper & PnB Rock) Ed Sheeran pop -6 79 206'

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
cv.fit(db['combined_features'])
# cv.vocabulary_

CountVectorizer()

In [17]:
cv.vocabulary_

{'se': 240,
 'orita': 207,
 'shawn': 244,
 'mendes': 194,
 'canadian': 106,
 'pop': 218,
 '55': 56,
 '191': 19,
 'china': 112,
 'anuel': 84,
 'aa': 78,
 'reggaeton': 227,
 'flow': 139,
 '81': 73,
 '302': 44,
 'boyfriend': 96,
 'with': 276,
 'social': 249,
 'house': 157,
 'ariana': 85,
 'grande': 147,
 'dance': 122,
 '80': 72,
 '186': 18,
 'beautiful': 91,
 'people': 214,
 'feat': 138,
 'khalid': 169,
 'ed': 130,
 'sheeran': 245,
 '65': 61,
 '198': 23,
 'goodbyes': 146,
 'young': 280,
 'thug': 265,
 'post': 219,
 'malone': 186,
 'dfw': 124,
 'rap': 223,
 '175': 12,
 'don': 127,
 'care': 109,
 'justin': 167,
 'bieber': 92,
 '68': 62,
 '220': 34,
 'ransom': 222,
 'lil': 177,
 'tecca': 262,
 'trap': 270,
 'music': 198,
 '64': 60,
 '131': 3,
 'how': 158,
 'do': 126,
 'you': 279,
 'sleep': 246,
 'sam': 238,
 'smith': 247,
 '202': 26,
 'old': 205,
 'town': 268,
 'road': 232,
 'remix': 228,
 'nas': 199,
 'country': 119,
 '62': 59,
 '157': 5,
 'bad': 88,
 'guy': 150,
 'billie': 94,
 'eilish': 1

In [18]:
 cv = cv.transform(db['combined_features']) 

In [19]:
cv

<50x282 sparse matrix of type '<class 'numpy.int64'>'
	with 430 stored elements in Compressed Sparse Row format>

In [20]:
from sklearn.metrics.pairwise import cosine_similarity
cs = cosine_similarity(cv)
print(cs)

[[1.         0.         0.1118034  ... 0.         0.         0.09805807]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.1118034  0.         1.         ... 0.         0.         0.0877058 ]
 ...
 [0.         0.         0.         ... 1.         0.         0.12403473]
 [0.         0.         0.         ... 0.         1.         0.09805807]
 [0.09805807 0.         0.0877058  ... 0.12403473 0.09805807 1.        ]]


In [21]:
cs.shape

(50, 50)

In [25]:
track_name = 'Happier'

In [26]:
music_id = db[db['Track.Name'] == track_name].index.values

In [27]:
music_id

array([47], dtype=int64)

In [28]:
selected_music_cs = cs[music_id]

In [29]:
selected_music_cs.shape

(1, 50)

In [30]:
type(selected_music_cs)

numpy.ndarray

In [31]:
sort_scores = np.argsort(selected_music_cs)

In [32]:
sort_scores.shape

(1, 50)

In [33]:
recommendation = sort_scores[:, sort_scores.shape[0]-12:-1]

In [34]:
recommendation

array([[17, 18, 19, 20, 12, 49, 22, 13, 29, 45]], dtype=int64)

In [35]:
type(recommendation.shape[1])

int

In [37]:
music = []
for i in range(0, recommendation.shape[1]):
  id = recommendation[0][i]
  music.append(db.iloc[id]['Track.Name'])

In [39]:
  music

['Sunflower - Spider-Man: Into the Spider-Verse',
 'Lalala',
 'Truth Hurts',
 'Piece Of Your Heart',
 'Someone You Loved',
 'Cross Me (feat. Chance the Rapper & PnB Rock)',
 'No Me Conoce - Remix',
 'Otro Trago - Remix',
 'QUE PRETENDES',
 'One Thing Right']